[workspace]
resolver = "3"
members = [
    "src/target",
    "src/ir",
    "src/emulator",
    "src/emulator/cli",
    "src/lift/aarch64",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[workspace.dependencies]
volt-ir = { path = "src/ir" }
volt-target = { path = "src/target" }
volt-emulator = { path = "src/emulator" }
volt-lift-aarch64 = { path = "src/lift/aarch64" }

object = { version = "0.40.0", default-features = false, features = ["read_core", "write_core", "elf", "macho"] }
libc = "0.2"
parking_lot = "0.12"
winnow-args = "0.1"
zrip = "0.8"

[workspace.lints.clippy]
std_instead_of_core = "deny"
std_instead_of_alloc = "warn"
alloc_instead_of_core = "warn"
too_many_arguments = "allow"

[profile.dev]
opt-level = 1
split-debuginfo = "packed"
debug = "line-tables-only"

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = "thin"
opt-level = 3
strip = true
